# Пусть Tmux берёт TERM от внешнего терминала
set-option -g default-terminal "#{TERM}"
# Говорим Tmux: «внешний терминал умеет true-color»
set-option -sa terminal-overrides ',*:Tc'

# Сортировка сессий по имени
bind s choose-tree -sZ -O name
# Изменение индексов вкладок
set -g base-index 1
setw -g pane-base-index 1
# Двойные рамки
set -g pane-border-lines "double"
# Ожидание после нажатия Esc
set -g escape-time 0
# Включение мыши
set -g mouse on

#Vim Key-map in copy ( prefix + [ )
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection 
bind-key -T copy-mode-vi 'y' send -X copy-selection 
unbind -T copy-mode-vi MouseDragEnd1Pane

# Основной префикс
set -g prefix C-q
# Key-map
## Разделение экрана
unbind %
bind | split-window -h 
unbind '"'
bind - split-window -v
## Перезагрузка конфига
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded :3"
## Изменение размера окон
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
# Режим навигации (перемещение панелей и между ними)
bind -r J swap-pane -D
bind -r K swap-pane -U
# Вращение панелей
bind -r o rotate-window -D   # по часовой
bind -r i rotate-window -U   # против часовой

# Отключение от сессии
bind q detach

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#Темы
set -g @plugin 'egel/tmux-gruvbox'
## Для работы с сессиями
set -g @plugin 'tmux-plugins/tmux-resurrect' 
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

set -g @plugin 'christoomey/vim-tmux-navigator'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


# Для работы с сессиями
set -g @resurrect-dir '~/.config/tmux/resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
